"""Initial Migration

Revision ID: 09fdecd17956
Revises: 
Create Date: 2021-11-29 15:17:27.361942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fdecd17956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=128), nullable=True),
    sa.Column('commit', sa.String(length=41), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.String(length=20), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commits')
    # ### end Alembic commands ###
