"""Initial Migration

Revision ID: 13156da5b4a6
Revises: 
Create Date: 2021-11-29 21:36:40.912681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13156da5b4a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('gh_repo', sa.String(), nullable=True),
    sa.Column('gl_repo', sa.String(), nullable=True),
    sa.Column('deploy_file', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('commit', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deploys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('cluster', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploys')
    op.drop_table('commits')
    op.drop_table('services')
    # ### end Alembic commands ###
