"""make deploy_file nullable

Revision ID: 76aa24144c5a
Revises: 13156da5b4a6
Create Date: 2021-11-29 21:50:31.150457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76aa24144c5a'
down_revision = '13156da5b4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'deploy_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'deploy_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
