"""Service unique constraint

Revision ID: 813953aff58c
Revises: 837d9ec82806
Create Date: 2021-11-29 16:34:11.250968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813953aff58c'
down_revision = '837d9ec82806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               primary_key=False)
    op.alter_column('services', 'service',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               primary_key=True)
    op.create_unique_constraint(None, 'services', ['service'])
    op.add_column('commits', sa.Column('service', sa.String(), nullable=True))
    op.create_foreign_key(None, 'commits', 'services', ['service'], ['service'])
    op.add_column('deploys', sa.Column('service', sa.String(), nullable=True))
    op.create_foreign_key(None, 'deploys', 'services', ['service'], ['service'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='unique')
    op.alter_column('services', 'service',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('services', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'deploys', type_='foreignkey')
    op.drop_column('deploys', 'service')
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_column('commits', 'service')
    # ### end Alembic commands ###
