"""Add remaining models

Revision ID: 837d9ec82806
Revises: 09fdecd17956
Create Date: 2021-11-29 15:59:36.668728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837d9ec82806'
down_revision = '09fdecd17956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=True),
    sa.Column('namespace', sa.String(length=128), nullable=True),
    sa.Column('cluster', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=40), nullable=True),
    sa.Column('gh_repo', sa.String(length=128), nullable=True),
    sa.Column('gl_repo', sa.String(length=128), nullable=True),
    sa.Column('deploy_file', sa.String(length=128), nullable=True),
    sa.Column('namespace', sa.String(length=50), nullable=True),
    sa.Column('branch_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('deploys')
    # ### end Alembic commands ###
