"""empty message

Revision ID: 9298b7dac752
Revises: e34d3ab48a5e
Create Date: 2021-11-30 09:56:46.609161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9298b7dac752'
down_revision = 'e34d3ab48a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'service', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='unique')
    # ### end Alembic commands ###
