"""remove branch from commit

Revision ID: ea42d275640c
Revises: 9298b7dac752
Create Date: 2021-11-30 13:38:12.635838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea42d275640c'
down_revision = '9298b7dac752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit', 'branch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
