FROM registry.redhat.io/ubi8/ubi-minimal

WORKDIR /app-root/

RUN microdnf install -y python39 python3-devel python3-pip

COPY Pipfile* /app-root/

RUN pip3 install pipenv
RUN pipenv install --system --deploy --ignore-pipfile

COPY . /app-root/
CMD bash -c 'flask db upgrade && ./run.sh'
